commonsense_qa: 
        test_split: validation 
        num_answer_choices: 5
        keyword: "commonsense reasoning"
        keylist: ["A", "B", "C", "D", "E"]
        instruction: The following are multiple-choice questions about everyday situations. 
            For the question below, select the most suitable answer from the 5 options given.
        tasks: ["commonsense_qa"]
openbookqa:
        test_split: "test"
        num_answer_choices: 4
        keyword: "science"
        keylist: ["A", "B", "C", "D"]
        instruction: The following are elementary-level multiple-choice questions about science. 
            For the question below, select the most suitable answer from the 4 options given.
        tasks: ["openbookqa"]
mmlu:
        test_split: "test"
        num_answer_choices: 4
        keyword: "multiple-choice"
        keylist: ["A", "B", "C", "D"]
        # for MMLU instructions, tasks descriptions will vary. Add during prompt construction.
        instruction: For the question below, select the most suitable answer from the 4 options given.
        tasks: [
                "abstract_algebra",
                "anatomy",
                "astronomy",
                "business_ethics",
                "clinical_knowledge",
                "college_biology",
                "college_chemistry",
                "college_computer_science",
                "college_mathematics",
                "college_medicine",
                "college_physics",
                "computer_security",
                "conceptual_physics",
                "econometrics",
                "electrical_engineering",
                "elementary_mathematics",
                "formal_logic",
                "global_facts",
                "high_school_biology",
                "high_school_chemistry",
                "high_school_computer_science",
                "high_school_european_history",
                "high_school_geography",
                "high_school_government_and_politics",
                "high_school_macroeconomics",
                "high_school_mathematics",
                "high_school_microeconomics",
                "high_school_physics",
                "high_school_psychology",
                "high_school_statistics",
                "high_school_us_history",
                "high_school_world_history",
                "human_aging",
                "human_sexuality",
                "international_law",
                "jurisprudence",
                "logical_fallacies",
                "machine_learning",
                "management",
                "marketing",
                "medical_genetics",
                "miscellaneous",
                "moral_disputes",
                "moral_scenarios",
                "nutrition",
                "philosophy",
                "prehistory",
                "professional_accounting",
                "professional_law",
                "professional_medicine",
                "professional_psychology",
                "public_relations",
                "security_studies",
                "sociology",
                "us_foreign_policy",
                "virology",
                "world_religions",
        ]